[build-system]
# Minimum requirements for the build system to execute.
requires = [
    "setuptools>=38.6.0",
    "setuptools-scm",
    "wheel>=0.31.0",
    "versioneer-518",
    "bcolz-zipline>=1.2.2",
    "Cython>=0.29.21,<3",
    "oldest-supported-numpy; python_version>='3.7'",
]
# uncomment to enable pep517 after versioneer problem is fixed.
# https://github.com/python-versioneer/python-versioneer/issues/193
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ['py37', 'py38']
exclude = '''
(
    asv_bench/env
  | \.egg
  | \.git
  | \.hg
  | _build
  | build
  | dist
  | setup.py
)
'''
