name: Zipline conda distribution

on: [ push ]

jobs:
  build_wheels:
    name: py${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      MACOSX_DEPLOYMENT_TARGET: 10.15
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        #        os: [ windows-latest ]
        python: [ '3.7', '3.8', '3.9' ]
        exclude:
          - os: macos-latest
            python: 39

    steps:
      - name: set Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        if: ${{ matrix.os == 'macos-latest' }}
        with:
          xcode-version: '11.5'

      - name: Checkout zipline-reloaded
        uses: actions/checkout@v2

      - name: Setup miniconda3
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          python-version: ${{ matrix.python }}
          activate-environment: recipe
          channels: ml4t, conda-forge, defaults, anaconda

      - name: conda install
        run: |
          conda activate recipe
          conda update conda -y
          conda install -n recipe conda-build conda-verify anaconda-client

      - name: conda build for ${{ matrix.os }}
        run: |
          conda-build --output-folder . --python ${{ matrix.python }} conda/zipline-reloaded/

      - name: store macos result
        uses: actions/upload-artifact@v2
        if: ${{ matrix.os == 'macos-latest' }}
        with:
          path: osx-64/*.tar.bz2

      - name: store linux result
        uses: actions/upload-artifact@v2
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          path: linux-64/*.tar.bz2

      - name: store windows result
        uses: actions/upload-artifact@v2
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          path: win-64/*.tar.bz2

      - name: upload macos
        if: ${{ matrix.python != '3.9'}} && ${{ matrix.ox == "macos-latest" }}
        run: anaconda upload -l main -u ml4t osx-64/*.tar.bz2

      - name: upload linux
        if: ${{ matrix.python != '3.9'}} && ${{ matrix.ox == "ubuntu-latest" }}
        run: anaconda upload -l main -u ml4t linux-64/*.tar.bz2

      - name: upload window
        if: ${{ matrix.python != '3.9'}} && ${{ matrix.ox == "windows-latest" }}
        run: anaconda upload -l main -u ml4t win-64/*.tar.bz2
